## List

### List are stored in square bracket .

In [1]:
listofInt= [1 , 3 , 5 , 8.0 , "a"]


In [2]:
len(listofInt)

5

In [3]:
listofInt[-2]

8.0

##### List is mutable 

In [5]:
a=[1,2]
b=[3,4]

In [8]:
c=[a,b]
print(c)

[[1, 2], [3, 4]]


First will row ,second will tell column


In [9]:
c[1],[0]

([3, 4], [0])

In [10]:
a*2

[1, 2, 1, 2]

when we don't want to change value in the list 


In [11]:
a=(10,11)# tuple
a[0]

10

Seta is a list of unique value


In [12]:
seta={1,2,3} #seta
print(seta)


{1, 2, 3}


## Dictionary

In [13]:
dictionaryA={"name" : "Dhruv" , "Batch" :"B1"}
# key:value
print(dictionaryA)

{'name': 'Dhruv', 'Batch': 'B1'}


In [14]:
dictionaryA["Batch"]

'B1'

In [18]:
help(dictionaryA)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
 |  Built-in subclasses:
 |      StgDict
 |
 |  Methods defined here:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __init

Ques - Write a program that take user input in numeric form and print it in table form

In [ ]:
Sol

In [19]:
num =int(input("Enter the number"))

Enter the number 5


In [21]:
for i in range (1,11):
    print(f"{num} x {i} ={num*i}") 


5 x 1 =5
5 x 2 =10
5 x 3 =15
5 x 4 =20
5 x 5 =25
5 x 6 =30
5 x 7 =35
5 x 8 =40
5 x 9 =45
5 x 10 =50


## Functions and arguments

In [23]:
## def functionName(arguments,arguments):
    #function defination

Ques - Write a function that gives us sum , average,min and max of all the value passed as arguments . like 10,20.30

In [25]:
infofn(10,20,30)


NameError: name 'infofn' is not defined

In [1]:
def fun(num1 ,num2 ,num3):
    sum=num1+num2+num3
    average=sum/3

    print(f"(sum of values is : {sum}")
    print(f"(average of value : {average}")
    


## Naming variable 
Snake case


Question - Create a list a size A user have 3*3 matrix store the matrix in a variable copy this matrix is another variable and then in the copied matrix multiply each value by constant and store the result in place after this step print both the matrix ?


In [1]:
import numpy as np

# Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Copy the matrix to another variable
B = A.copy()

# Multiply each value in the copied matrix by a constant, e.g., 2
B = B * 2

# Print both matrices
print("Original Matrix (A):")
print(A)

print("\nModified Matrix (B) after multiplication by 2:")
print(B)


Original Matrix (A):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified Matrix (B) after multiplication by 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Deep copy concept



In [ ]:
import copy 